# Generated by Django 5.0.6 on 2024-05-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0005_remove_films_categorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acteurs',
            new_name='Acteur',
        ),
        migrations.RenameModel(
            old_name='Films',
            new_name='Film',
        ),
    ]
