# Generated by Django 5.0.6 on 2024-05-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0003_alter_acteurs_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteurs',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='films',
            name='affiche',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='affiches/'),
        ),
    ]
