# Generated by Django 5.0.6 on 2024-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0002_alter_acteurs_photos_alter_films_affiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteurs',
            name='photos',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/'),
        ),
    ]
