# Generated by Django 5.0.6 on 2024-05-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0004_alter_acteurs_photos_alter_films_affiche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='categorie',
        ),
    ]
