# Generated by Django 5.0.6 on 2024-06-12 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0009_commentaire_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='film',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='filmographie.film'),
        ),
    ]
