# Generated by Django 5.0.6 on 2024-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0011_alter_acteur_photos_alter_film_affiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='affiche',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='affiche/'),
        ),
    ]
